plugin: amazon.aws.aws_ec2
regions:
  - ap-southeast-2
filters:
  tag:Role: ['realm', 'nonrealm']
  tag:Deployment: "infinia"
use_extra_vars: true
keyed_groups:
  - prefix: role
    key: tags['Role']
hostnames:
  - instance-id