plugin: aws_ec2
regions:
  - us-east-1
filters:
  tag:Role: ['realm', 'nonrealm']  # Include only instances with these roles
keyed_groups:
  - prefix: role
    key: tags['Role']
hostnames:
  - instance-id