---
- name: Setup Infinia Environment
  hosts: all
  become: yes
  vars:
    infinia_version: "2.2.9"
    base_pkg_url: "https://storage.googleapis.com/ddn-redsetup-public"
    release_type: ""
    rel_dist_path: "ubuntu/24.04"

  tasks:
    - name: Set environment variables
      ansible.builtin.set_fact:
        TARGET_ARCH: "{{ ansible_architecture }}"
        REL_PKG_URL: "{{ base_pkg_url }}/releases{{ release_type }}/{{ rel_dist_path }}"
        RED_VER: "{{ infinia_version }}"

    - name: Install lldpd
      ansible.builtin.apt:
        name: lldpd
        state: present
        update_cache: yes

    - name: Enable and restart lldpd if service exists
      ansible.builtin.shell: |
        if systemctl list-units --type=service | grep -q lldpd.service; then
          systemctl enable lldpd && systemctl restart lldpd
        else
          echo 'lldpd.service not found, skipping...'
        fi

    - name: Download redsetup package
      ansible.builtin.get_url:
        url: "{{ base_pkg_url }}/releases{{ release_type }}/{{ rel_dist_path }}/redsetup_{{ infinia_version }}_amd64{{ release_type }}.deb?cache-time={{ ansible_date_time.epoch }}"
        dest: /tmp/redsetup.deb

    - name: Install redsetup package
      ansible.builtin.apt:
        deb: /tmp/redsetup.deb

    - name: Download rmd_template.json
      ansible.builtin.get_url:
        url: "{{ base_pkg_url }}/releases/rmd_template.json"
        dest: /tmp/rmd_template.json

    - name: Substitute environment variables in rmd_template.json
      ansible.builtin.shell: |
        envsubst < /tmp/rmd_template.json > /tmp/rmd.json
      environment:
        INFINIA_VERSION: "{{ infinia_version }}"
        BASE_PKG_URL: "{{ base_pkg_url }}"
        RELEASE_TYPE: "{{ release_type }}"
        REL_DIST_PATH: "{{ rel_dist_path }}"
    
    - name: Remove config lock from ami 
      file: 
        path: /etc/red/deploy/config.lock
        state: absent
      become: true
         
    
    - name: Reset redsetup
      ansible.builtin.shell: redsetup -reset


    - name: Run redsetup with realm entry
      ansible.builtin.shell: >
        redsetup -realm-entry -realm-entry-secret PA-ssW00r^d
        --admin-password PA-ssW00r^d
        -ctrl-plane-ip $(hostname --ip-address)
        -release-metadata-file /tmp/rmd.json
        -skip-reboot -skip-hardware-check

    - name: Clean apt cache and temporary files
      ansible.builtin.shell: |
        rm -rf /var/cache/apt /tmp/*
        apt-get autoremove -y && apt-get clean
        rm -rf /var/lib/apt/lists/*
        journalctl --rotate && journalctl --vacuum-time=1s
        rm -rf /var/log/* /tmp/* /var/tmp/*

