apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: High-Performance Infinia solution
  annotations:
    autogenSpecType: MULTI_VM
    config.kubernetes.io/local-config: "true"
spec:
  info:
    author:
      title: DDN
      description: >-
        DDN is a leading provider of data intelligence solutions, delivering cutting-edge 
        platforms that transform how organizations harness information for AI and 
        data-intensive workloads. Trusted by industry leaders like NVIDIA and xAI.
        Leading provider of intelligent data platforms for AI and data-intensive workloads,
        delivering unmatched performance and scalability.
    title: High-Performance Infinia solution
    source:
      sourceType: git
      repo: https://github.red.datadirectnet.com/red/infinia-hp-gcp-mp.git
  ui:
    input:
      variables:
        source_image:
          name: source_image
          title: Image version
          xGoogleProperty:
            type: ET_GCE_DISK_IMAGE
          enumValueLabels:
            - label: ddn-infinia-2-0-23-ubuntu-2404-amd-2025-03-31
              value: projects/ddn-public/global/images/ddn-infinia-2-0-23-ubuntu-2404-amd-2025-03-31
        desired_capacity:
          name: desired_capacity
          title: Desired capacity in TB. Minimum is 63TB.
          min: 63
          max: 10240
          section: desired_capacity
        num_clients:
          name: num_clients
          title: Number of client VMs to create.
          min: 0
          section: clients
        enable_cloud_logging:
          name: enable_cloud_logging
          title: Enable Cloud Logging
          tooltip: Cloud Logging allows you to store, search, analyze, monitor, and alert on log data and events. <a href="https://cloud.google.com/logging/">Learn more</a>
          section: google_cloud_operations
        enable_cloud_monitoring:
          name: enable_cloud_monitoring
          title: Enable Cloud Monitoring
          tooltip: Cloud Monitoring provides visibility into the performance, uptime, and overall health of cloud-powered applications. <a href="https://cloud.google.com/monitoring/">Learn more</a>
          section: google_cloud_operations
        enable_tcp_443:
          name: enable_tcp_443
          title: Allow HTTPS traffic from the Internet
          section: networking
          xGoogleProperty:
            type: ET_GCE_FIREWALL
            gceFirewall:
              networkVariable: networks
        tcp_443_source_ranges:
          name: tcp_443_source_ranges
          title: Source IP ranges for HTTPS traffic
          tooltip: Traffic is only allowed from sources within these IP address ranges. Use CIDR notation when entering ranges. <a href="https://cloud.google.com/compute/docs/networking#firewalls">Learn more</a>
          placeholder: 0.0.0.0/0, 192.169.0.2/24
          section: networking
          xGoogleProperty:
            type: ET_GCE_FIREWALL_RANGE
            gceFirewallRange:
              firewallVariable: enable_tcp_443
        external_ips:
          name: external_ips
          title: External IP
          tooltip: An external IP address associated with this instance. Selecting "None" will result in the instance having no external internet access. <a href="https://cloud.google.com/compute/docs/configure-instance-ip-addresses">Learn more</a>
          minItems: 1
          maxItems: 8
          section: networking
          xGoogleProperty:
            type: ET_GCE_EXTERNAL_IP
            gceExternalIp:
              networkVariable: networks
              allowStaticIps: true
        goog_cm_deployment_name:
          name: goog_cm_deployment_name
          title: Goog Cm Deployment Name
        httpsEnabled:
          name: httpsEnabled
          title: HTTPS Enabled
          subtext: Enabled HTTPS communication.
        infinia_license:
          name: infinia_license
          title: Infinia License
          section: license
        networks:
          name: networks
          title: Network name
          minItems: 1
          maxItems: 8
          section: networking
          xGoogleProperty:
            type: ET_GCE_NETWORK
            gceNetwork:
              allowSharedVpcs: true
              machineTypeVariable: machine_type
        project_id:
          name: project_id
          title: Project Id
          invisible: true
        sub_networks:
          name: subnetworks
          title: Subnetwork name
          minItems: 1
          maxItems: 8
          section: networking
          xGoogleProperty:
            type: ET_GCE_SUBNETWORK
            zoneProperty: zone
            gceSubnetwork:
              networkVariable: networks
        tcp_80_source_ranges:
          name: tcp_80_source_ranges
          title: Source IP ranges for HTTP traffic
          tooltip: Traffic is only allowed from sources within these IP address ranges. Use CIDR notation when entering ranges. <a href="https://cloud.google.com/compute/docs/networking#firewalls">Learn more</a>
          placeholder: 0.0.0.0/0, 192.169.0.2/24
          section: networking
          xGoogleProperty:
            type: ET_GCE_FIREWALL_RANGE
            gceFirewallRange:
              firewallVariable: enable_tcp_80
        zone:
          name: zone
          title: Zone
          xGoogleProperty:
            type: ET_GCE_ZONE
      sections:
        - name: desired_capacity
          title: Desired Capacity
          tooltip: Desired capacity in TB. Minimum is 63TB.
        - name : clients
          title: Number of Clients (Optional)
        - name: license
          title: Licensing
          subtext: A valid license key is required for deployment. Please contact DDN Sales to obtain a license.
        - name: networking
          title: Networking
        - name: google_cloud_operations
          title: Google Cloud Operations
          subtext: Monitoring and management for services, containers, applications, and infrastructure
    runtime:
      suggestedActions:
        - heading: Cluster creation using UI
          description: |
            <h4>Follow these steps:</h4>
            <ol>
              <li>Login to <code>https://{First Instance Nat IP}</code> from deployment outputs</li>
              <li>Use username: <code>realm_admin</code></li>
              <li>Use password: <code>{Admin Password}</code> from deployment outputs</li>
              <li>Follow the documentation at <a href="https://www.ddn.com/products/infinia/">DDN Infinia</a> for cluster creation and configuration</li>
            </ol>
        - heading: Cluster creation using CLI
          description: |
            <h4>Follow these steps:</h4>
            <ol>
              <li>SSH into the <code>{First Instance Nat IP}</code> from deployment outputs</li>
              <li>Run: <code>redcli user login realm_admin</code></li>
              <li>Use <code>{Admin Password}</code> from deployment outputs</li>
              <li>Follow the documentation at <a href="https://www.ddn.com/products/infinia/">DDN Infinia</a> for cluster creation and configuration</li>
            </ol>
        - heading: Important Security Note
          description: |
            For security purposes, please change both the Admin Password and Realm Entry Secret after your first login
