name: Create GCP VM Image

on:
  workflow_dispatch:
    inputs:
      INFINIA_VERSION:
        description: "Version of Infinia"
        required: true
      GCP_PROJECT:
        description: "GCP Project"
        required: false
        default: red-101

jobs:
  create-image:
    runs-on: small-dynamic-amd64-u24
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - uses: hashicorp/setup-terraform@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'   

      - name: Authenticate to Google Cloud with SA JSON file
        run: |
          SA_FILE=$(ls gha-*.json)
          gcloud auth activate-service-account --key-file=${{ github.workspace }}/${SA_FILE}
          gcloud config set project ${{ inputs.GCP_PROJECT }}

      - name: Initialize Terraform
        working-directory: ./vm-images/gcp/terraform
        run: terraform init

      - name: Plan Terraform
        working-directory: ./vm-images/gcp/terraform
        run: terraform plan -var="infinia_version=${{ inputs.INFINIA_VERSION }}" -var="project_id=${{ inputs.GCP_PROJECT }}"

      - name: Apply Terraform
        working-directory: ./vm-images/gcp/terraform
        run: terraform apply -auto-approve -var="infinia_version=${{ inputs.INFINIA_VERSION }}" -var="project_id=${{ inputs.GCP_PROJECT }}"

      - name: Cleanup and Destroy Terraform Resources
        if: always()
        working-directory: ./vm-images/gcp/terraform
        run: terraform destroy -auto-approve -var="infinia_version=${{ inputs.INFINIA_VERSION }}" -var="project_id=${{ inputs.GCP_PROJECT }}"
