name: Destroy Infinia Infrastructure

on:
  workflow_call:
    inputs:
      aws_region:
        description: "AWS Region"
        required: true
        type: string
env:
  TERRAFORM_DIR: deployments/aws

jobs:
  destroy-infinia:
    name: Destroy Infrastructure
    runs-on: small-dynamic-amd64-u24

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws_region }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Destroy
        working-directory: ${{ env.TERRAFORM_DIR }}
        run: |
          terraform destroy -auto-approve