name: Infinia Build, Deploy and Cleanup

on:
  workflow_dispatch:
    inputs:
      aws_region:
        description: "AWS Region"
        required: true
        type: string
      deployment_name:
        description: "Deployment Name"
        required: true
        type: string
      infinia_version:
        description: "Infinia Version"
        required: true
        type: string

env:
  AWS_REGION: ${{ inputs.aws_region }}

jobs:
  packer-build:
    name: Build Packer AMI
    uses: ./.github/workflows/packer-build-aws.yml
    with:
      aws_region: ${{ inputs.aws_region }}
      infinia_version: ${{ inputs.infinia_version }}
    secrets: inherit

  infinia-deploy:
    name: Deploy Infinia Infrastructure
    needs: packer-build
    uses: ./.github/workflows/infinia-deploy-aws.yml
    with:
      ami_id: ${{ needs.packer-build.outputs.ami_id }}
      aws_region: ${{ inputs.aws_region }}
      deployment_name: ${{ inputs.deployment_name }}
      infinia_version: ${{ inputs.infinia_version }}
    secrets: inherit

  infinia-destroy:
    name: Destroy Infinia Infrastructure
    needs: infinia-deploy
    uses: ./.github/workflows/infinia-destroy-aws.yml
    with:
      aws_region: ${{ inputs.aws_region }}
    secrets: inherit
