name: Infinia Build, Deploy and Cleanup

on:
  push:
    branches:
      - one-click-aws
  # workflow_dispatch:
  #   inputs:
  #     aws_region:
  #       description: "AWS Region"
  #       required: true
  #       type: string
  #     # deployment_name:
  #     #   description: "Deployment Name"
  #     #   required: true
  #     #   type: string
  #     infinia_version:
  #       description: "Infinia Version"
  #       required: true
  #       type: string
      # s3_bucket_name:
      #   description: "Terraform S3 Backend Bucket Name"
      #   required: true
      #   type: string
      # s3_bucket_region:
      #   description: "Terraform S3 Backend Bucket Region"
      #   required: true
      #   type: string
      # vpc_id:
      #   description: "VPC ID"
      #   required: true
      #   type: string
      # subnet_ids:
      #   description: "Comma-separated Subnet IDs"
      #   required: true
      #   type: string
      # security_group_id:
      #   description: "Security Group ID"
      #   required: true
      #   type: string
      # bucket_name:
      #   description: "S3 Bucket for Ansible SSM"
      #   required: true
      #   type: string
      # num_client_instances:
      #   description: "Number of client instances"
      #   required: true
      #   type: number

env:
  aws_region: us-east-1
  infinia_version: 2.2.60

jobs:
  packer-build:
    name: Build Packer AMI
    uses: ./.github/workflows/packer-build-aws.yml
    with:
      aws_region: us-east-1
      infinia_version: 2.2.60
    secrets: inherit

  infinia-deploy:
    name: Deploy Infinia Infrastructure
    needs: packer-build
    uses: ./.github/workflows/infinia-deploy-aws.yml
    with:
      aws_region: us-east-1
      ami_id: ${{ needs.packer-build.outputs.ami_id }}
      infinia_version: 2.2.60
    secrets: inherit

  # infinia-destroy:
  #   name: Destroy Infinia Infrastructure
  #   needs: infinia-deploy
  #   if: always()
  #   uses: ./.github/workflows/infinia-destroy-aws.yml
  #   with:
  #     aws_region: us-east-1
  #   #   infinia_version: ${{ inputs.infinia_version }}
  #   secrets: inherit
