name: Build Infinia AMI with Packer

on:
  workflow_call:
    inputs:
      aws_region:
        description: "AWS Region"
        required: true
        type: string
      infinia_version:
        description: "Infinia Version"
        required: true
        type: string
    outputs:
      ami_id:
        description: "Built AMI ID"
        value: ${{ jobs.packer-build.outputs.ami_id }}

jobs:
  packer-build:
    name: Build Packer Template
    runs-on: small-dynamic-amd64-u24
    defaults:
      run:
        working-directory: vm-images/aws/packer

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws_region }}

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        with:
          version: "latest"

      - name: Run `packer init`
        run: |
          packer init template.pkr.hcl

      # Step 3: Validate Packer template with conditional argument
      - name: Validate Packer template
        run: |
          if [ -n "${{ github.event.inputs.infinia_version }}" ]; then
            packer validate -var "infinia_version=${{ github.event.inputs.infinia_version }}" -var-file=aws.pkrvars.hcl template.pkr.hcl
          else
            packer validate -var-file=aws.pkrvars.hcl template.pkr.hcl
          fi

      # Step 4: Format Packer template
      - name: Format Packer template
        run: |
          packer fmt -write template.pkr.hcl

      # Step 5: Build the Packer template with conditional argument
      - name: Build AMI with Packer
        run: |
          if [ -n "${{ github.event.inputs.infinia_version }}" ]; then
            packer build -var "infinia_version=${{ github.event.inputs.infinia_version }}" -var-file=aws.pkrvars.hcl template.pkr.hcl
          else
            packer build -var-file=aws.pkrvars.hcl template.pkr.hcl
          fi
          echo "::set-output name=ami_id::$AMI_ID"

      - name: Capture AMI ID
        id: capture-ami-id
        run: echo "::set-output name=ami_id::$AMI_ID"
      # Step 7: Notify Build Success
      - name: Notify Build Success
        run: echo "Packer build completed successfully!"
