name: Build Infinia AMI with Packer

on:
  push:
    branches:
      - add-packer # Trigger on push to the add-packer branch

jobs:
  packer-build:
    name: Build Packer Template
    runs-on: small-dynamic-amd64-u24
    defaults:
      run:
        working-directory: vm-images/aws/packer

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        with:
          version: "latest"

      - name: Run `packer init`
        run: |
          packer init template.pkr.hcl

      # Step 3: Validate Packer template
      - name: Validate Packer template
        run: |
          packer validate -var-file=aws.pkrvars.hcl template.pkr.hcl

      # Step 4: Format Packer template
      - name: Format Packer template
        run: |
          packer fmt -write packer-template.pkr.hcl

      # Step 5: Build the Packer template
      - name: Build AMI with Packer
        run: |
          packer build -var-file=aws.pkrvars.hcl template.pkr.hcl

      # Step 6: Notify Build Success
      - name: Notify Build Success
        run: echo "Packer build completed successfully!"
